[package]
name = "universal-weave"
version = "0.4.3"
authors = [
	"transkatgirl",
]
license = "Unlicense"
description = "General-purpose building blocks for Loom implementations."
categories = [
	"data-structures",
	"no-std",
]
keywords = [
	"loom",
	"weave",
	"graph",
	"storage",
]
repository = "https://github.com/transkatgirl/universal-weave"
edition = "2024"

[features]
default = [ "rkyv" ]
rkyv = [
	"dep:rkyv",
]
loro = [
	"rkyv",
	"dep:loro",
	"dep:loro-internal",
]
serde = [
	"dep:serde",
	"hashbrown/serde",
	"indexmap/serde",
]

# A deprecated version of DependentWeave used by `tapestry-weave`'s v0 format; Please don't use this!
legacy = [  ]


[dependencies]
contracts = "0.6.10"
scratchpads = "0.1.0"
hashbrown = { version = "0.17.1", features = [
	"allocator-api2",
	# Hashbrown's default (non-DOS-resistant) hasher is only used in two places: Function contracts (only enabled in debug mode) and Archived versions of the built-in Weave implementations (which were already, by their very nature, vulnerable to hash collision attacks).
	"default-hasher",
	"inline-more",
], default-features = false }
indexmap = { version = "2.14.0", default-features = false }
rkyv = { version = "0.8.18", features = [
	"alloc",
	"bytecheck",
	"hashbrown-0_17",
	"indexmap-2",
], default-features = false, optional = true }
loro = { version = "=1.13.6", optional = true } # Workaround for https://github.com/loro-dev/loro/issues/1046
loro-internal = { version = "=1.13.6", optional = true } # Workaround for https://github.com/loro-dev/loro/issues/1046; No loro-internal functions are called directly
serde = { version = "1.0.229", features = [
	"alloc",
	"derive",
], default-features = false, optional = true }


[dev-dependencies]
proptest               = "1.11.0"
proptest-state-machine = "0.8.0"
proptest-derive        = "0.8.0"
old_universal_weave    = { package = "universal-weave", version = "=0.4.0" }

[profile.test.build-override]
opt-level = 2

[profile.test.package.proptest]
opt-level = 3

[profile.test.package.rand_chacha]
opt-level = 3

[[test]]
name = "archived_dependent"
required-features = [
	"rkyv",
]

[[test]]
name = "archived_independent"
required-features = [
	"rkyv",
]

[[test]]
name = "loro_dependent"
required-features = [
	"loro",
]

[[test]]
name = "loro_dependent_merge"
required-features = [
	"loro",
]

[[test]]
name = "loro_dependent_merge_three_way"
required-features = [
	"loro",
]
